// Main3 task 8.9: tower sightline check (Main3.md 5.3, 5.7 W-1 and C-1, 4.1). Edit mode, Main3 open; changes nothing that
// is saved (temporary crown colliders are removed before it returns). Writes Docs/Layout/Main3/Main3_sightlines.md.
// Eyes: a 1 m grid over the 8 x 8 m deck (64 points) at eye height 57.6 and jump height 58.2, then both raised 3 m.
// Tower geometry is ignored (the player can stand anywhere on the deck).
// Places: a target is seen if a ray reaches it (a hit within 2 m of the target counts); margin = how far the best line
//   passes above anything under it (terrain, rock, buildings, giants with crowns), from the eye to 5 m short of the target.
// W-1 / C-1 (trees off): rays to every Ward stone corner and every cave mouth corner must hit the Tor or terrain; hidden
//   margin = how deep the least-hidden line passes under the blocking surface. Repeated with eyes and targets raised 3 m.
// 4.1: from each junction at 1.6 m eye height, is any part of the cab visible (trees on)?
if (UnityEngine.Application.isPlaying) return "stop play mode first";
var scene = UnityEngine.SceneManagement.SceneManager.GetActiveScene();
if (scene.path != "Assets/Scenes/Main3.unity") return "open Main3 first";
UnityEngine.GameObject Root(string name) { foreach (var r in scene.GetRootGameObjects()) if (r.name == name) return r; return null; }
var V = new System.Func<float, float, float, UnityEngine.Vector3>((x, y, z) => new UnityEngine.Vector3(x, y, z));
var terrain = Root("Terrain").GetComponent<UnityEngine.Terrain>(); float baseY = terrain.transform.position.y;
float Hg(float x, float z) => terrain.SampleHeight(V(x, 0f, z)) + baseY;
var tower = Root("Camp").transform.Find("Tower"); var giants = Root("Giants").transform; var wardRoot = Root("Ward").transform;
var thicketRoot = Root("Thicket") != null ? Root("Thicket").transform : null;   // counts as trees: off for W-1 and C-1
bool wasDirty = scene.isDirty;
// temporary colliders on the crowns so trees block lines (they have none in the scene)
var temp = new System.Collections.Generic.List<UnityEngine.Component>();
foreach (var mf in giants.GetComponentsInChildren<UnityEngine.MeshFilter>()) if (mf.name == "Crown" && mf.GetComponent<UnityEngine.Collider>() == null) temp.Add(mf.gameObject.AddComponent<UnityEngine.MeshCollider>());
UnityEngine.Physics.SyncTransforms();
bool IsUnder(UnityEngine.Transform t, UnityEngine.Transform root) { for (var p = t; p != null; p = p.parent) if (p == root) return true; return false; }
// first hit along a segment that is not the tower (and, with trees off, not a giant)
bool FirstHit(UnityEngine.Vector3 a, UnityEngine.Vector3 b, bool treesOn, out UnityEngine.RaycastHit hit)
{
    var d = b - a; var hits = UnityEngine.Physics.RaycastAll(a, d.normalized, d.magnitude, ~0, UnityEngine.QueryTriggerInteraction.Ignore);
    System.Array.Sort(hits, (p, q) => p.distance.CompareTo(q.distance));
    foreach (var h in hits) { if (IsUnder(h.collider.transform, tower)) continue; if (!treesOn && (IsUnder(h.collider.transform, giants) || (thicketRoot != null && IsUnder(h.collider.transform, thicketRoot)))) continue; hit = h; return true; }
    hit = default; return false;
}
// height of whatever is under (x, z): terrain, rock, buildings, and giants when trees are on
float Surface(float x, float z, bool treesOn)
{
    var hits = UnityEngine.Physics.RaycastAll(V(x, 200f, z), UnityEngine.Vector3.down, 260f, ~0, UnityEngine.QueryTriggerInteraction.Ignore);
    float best = -999f; foreach (var h in hits) { if (IsUnder(h.collider.transform, tower)) continue; if (!treesOn && (IsUnder(h.collider.transform, giants) || (thicketRoot != null && IsUnder(h.collider.transform, thicketRoot)))) continue; if (h.point.y > best) best = h.point.y; }
    return best;
}
// line clearance: min over samples of (line - surface), from 3 m after the eye to 'endSkip' short of the target
float Clearance(UnityEngine.Vector3 a, UnityEngine.Vector3 b, bool treesOn, float endSkip)
{
    float len = UnityEngine.Vector3.Distance(a, b), best = float.MaxValue;
    for (float s = 3f; s < len - endSkip; s += 1.5f) { var p = UnityEngine.Vector3.Lerp(a, b, s / len); best = UnityEngine.Mathf.Min(best, p.y - Surface(p.x, p.z, treesOn)); }
    return best;
}
var eyes = new System.Collections.Generic.List<UnityEngine.Vector2>();
for (float gx = -3.5f; gx <= 3.5f; gx += 1f) for (float gz = -3.5f; gz <= 3.5f; gz += 1f) eyes.Add(new UnityEngine.Vector2(tower.position.x + gx, tower.position.z + gz));
float deckTop = tower.position.y + 48f; var heights = new[] { ("eye", deckTop + 1.6f), ("jump", deckTop + 2.2f) };
var md = new System.Text.StringBuilder();
md.AppendLine("# Main3 tower sightlines (task 8.9)\n");
md.AppendLine("Generated by Tools/Recipes/main3_8_9_sightlines.cs from the gray blockout. Eyes: 1 m grid over the 8 x 8 m deck (64 points), eye 57.6 m and jump 58.2 m, then both raised 3 m. Tower geometry ignored. Margins in metres.\n");

// ---------------- places ----------------
var places = new (string place, (string n, UnityEngine.Vector3 p)[] targets)[] {
    ("Lake", new[] { ("far water (south shore)", V(190f, -5.4f, 34f)), ("mid water", V(190f, -5.4f, 60f)), ("near water", V(190f, -5.4f, 86f)), ("boathouse roof", V(240f, -1.0f, 52.4f)) }),
    ("Camp 1", new[] { ("spar top", V(282f, 29f, 238f)), ("spar at 20 m", V(282f, 20f, 238f)), ("tent", V(292f, Hg(292f, 247f) + 2f, 247f)) }),
    ("Camp 2", new[] { ("stack top", V(292f, 24.2f, 108f)), ("stack west edge", V(287.4f, 23.6f, 108f)), ("boulder field", V(274f, Hg(274f, 104f) + 1f, 104f)) }),
    ("Camp 3", new[] { ("Snag top", V(96f, 54f, 146.5f)), ("Snag at 40 m, east face", V(98.9f, 40f, 147.2f)) }),
    ("Office and lot", new[] { ("lot west edge", V(343.5f, 3.1f, 170f)), ("lot centre", V(358f, 3.1f, 170f)), ("resident's car", V(370f, 4.2f, 179.4f)), ("office roof", V(350f, 6.4f, 200f)), ("store roof", V(366f, 6.2f, 200f)), ("mast lamp", V(357f, 33.3f, 205f)) }),
};
md.AppendLine("## Places seen from the deck (trees on)\n");
md.AppendLine("| Place | Target | Seen from (eye) | Seen from (jump) | Best-line margin (eye) | Deck-centre margin (eye) |");
md.AppendLine("|---|---|---|---|---|---|");
var summary = new System.Text.StringBuilder(); bool allPlaces = true;
foreach (var pl in places)
{
    bool placeSeen = false;
    foreach (var t in pl.targets)
    {
        var seen = new int[2]; float bestMargin = float.MinValue;
        for (int hi = 0; hi < 2; hi++)
            foreach (var e in eyes)
            {
                var a = V(e.x, heights[hi].Item2, e.y); var toT = t.p - a; var end = t.p - toT.normalized * 0.3f;
                bool vis = !FirstHit(a, end, true, out var h) || UnityEngine.Vector3.Distance(h.point, t.p) < 2f;
                if (vis) seen[hi]++;
            }
        // margins from every eye at eye height (sampled every 1.5 m), best line reported; and from the deck centre
        foreach (var e in eyes) { var a = V(e.x, heights[0].Item2, e.y); bestMargin = UnityEngine.Mathf.Max(bestMargin, Clearance(a, t.p, true, 5f)); }
        float centreMargin = Clearance(V(tower.position.x, heights[0].Item2, tower.position.z), t.p, true, 5f);
        if (seen[0] > 0) placeSeen = true;
        md.AppendLine("| " + pl.place + " | " + t.n + " | " + seen[0] + "/64 | " + seen[1] + "/64 | " + bestMargin.ToString("F1") + " | " + centreMargin.ToString("F1") + " |");
    }
    if (!placeSeen) allPlaces = false;
    summary.Append(pl.place + (placeSeen ? " seen" : " NOT SEEN") + "; ");
}

// ---------------- W-1 and C-1 ----------------
var stoneCorners = new System.Collections.Generic.List<UnityEngine.Vector3>();
foreach (UnityEngine.Transform s in wardRoot.Find("Stones"))
{
    var b = s.GetComponent<UnityEngine.Renderer>().bounds;
    foreach (var cx in new[] { b.min.x, b.max.x }) foreach (var cz in new[] { b.min.z, b.max.z })
    { stoneCorners.Add(V(cx, b.max.y, cz)); stoneCorners.Add(V(cx, Hg(cx, cz) + 0.1f, cz)); }
}
var mouthCorners = new System.Collections.Generic.List<UnityEngine.Vector3> { V(50.5f, -6f, 37.4f), V(53.5f, -6f, 37.4f), V(50.5f, -2f, 37.4f), V(53.5f, -2f, 37.4f) };
md.AppendLine("\n## W-1 (Ward) and C-1 (cave), trees off\n");
md.AppendLine("Every ray must hit the Tor or the terrain before its target. Hidden margin: how deep the least-hidden line passes under the blocking surface.\n");
md.AppendLine("| Check | Eyes and targets | Rays | Rays blocked | Blocked by | Hidden margin, all eyes | Hidden margin, deck centre |");
md.AppendLine("|---|---|---|---|---|---|---|");
bool wardHidden = true, caveHidden = true; string headline = ""; float w1Plus3 = float.MaxValue;
foreach (var chk in new[] { ("W-1", stoneCorners), ("C-1", mouthCorners) })
    foreach (var raise in new[] { 0f, 3f })
        for (int hi = 0; hi < 2; hi++)
        {
            int rays = 0, blocked = 0; float worst = float.MaxValue, centreWorst = float.MaxValue; var by = new System.Collections.Generic.HashSet<string>();
            foreach (var e in eyes)
                foreach (var c in chk.Item2)
                {
                    var a = V(e.x, heights[hi].Item2 + raise, e.y); var tgt = c + V(0f, raise, 0f);
                    var end = tgt - (tgt - a).normalized * 0.4f; rays++;
                    bool hit = FirstHit(a, end, false, out var h);
                    bool ok = hit && (IsUnder(h.collider.transform, wardRoot.Find("Tor")) || h.collider is UnityEngine.TerrainCollider);
                    if (ok) { blocked++; by.Add(h.collider is UnityEngine.TerrainCollider ? "terrain" : "Tor"); }
                    // depth under the blocker: max over samples of (surface - line), trees off, stopping 3 m short of the target
                    float len = UnityEngine.Vector3.Distance(a, tgt), depth = float.MinValue;
                    for (float s = 3f; s < len - 3f; s += 1.5f) { var p = UnityEngine.Vector3.Lerp(a, tgt, s / len); depth = UnityEngine.Mathf.Max(depth, Surface(p.x, p.z, false) - p.y); }
                    worst = UnityEngine.Mathf.Min(worst, depth);
                    if (UnityEngine.Mathf.Abs(e.x - tower.position.x) < 0.6f && UnityEngine.Mathf.Abs(e.y - tower.position.z) < 0.6f) centreWorst = UnityEngine.Mathf.Min(centreWorst, depth);
                }
            if (blocked < rays) { if (chk.Item1 == "W-1") wardHidden = false; else caveHidden = false; }
            md.AppendLine("| " + chk.Item1 + " | " + (raise > 0f ? "+3 m, " : "") + heights[hi].Item1 + " | " + rays + " | " + blocked + " | " + string.Join(", ", by) + " | " + worst.ToString("F1") + " | " + centreWorst.ToString("F1") + " |");
            if (raise == 0f && hi == 0) headline += chk.Item1 + " hidden margin " + worst.ToString("F1") + " m (eye); ";
            if (raise == 3f && hi == 1) headline += chk.Item1 + " +3 m jump " + worst.ToString("F1") + " m; ";
            if (raise == 3f && chk.Item1 == "W-1") w1Plus3 = UnityEngine.Mathf.Min(w1Plus3, worst);
        }

// ---------------- 4.1: cab from the junctions ----------------
var cab = tower.Find("Cab");
var cabPts = new System.Collections.Generic.List<UnityEngine.Vector3>();
foreach (var cx in new[] { -2.2f, 0f, 2.2f }) foreach (var cz in new[] { -2.2f, 0f, 2.2f }) foreach (var cy in new[] { 1.0f, 2.7f }) cabPts.Add(cab.TransformPoint(V(cx, cy, cz)));
var junctions = new (string n, float x, float z)[] { ("J", 104f, 206f), ("Jg", 262f, 172f), ("W1", 128f, 70f), ("T", 340f, 170f), ("Pump", 190f, 97f), ("Camp 1", 276f, 232f), ("Camp 2 (stack foot)", 286f, 99f), ("Camp 3 floor", 78f, 146f) };
md.AppendLine("\n## 4.1 Tower cab seen from the junctions (eye 1.6 m, trees on)\n");
md.AppendLine("| Junction | Cab points seen (of " + cabPts.Count + ") | First blocker of a missed ray |");
md.AppendLine("|---|---|---|");
string junc = "";
foreach (var j in junctions)
{
    var a = V(j.x, Hg(j.x, j.z) + 1.6f, j.z); int seen = 0; string blocker = "";
    foreach (var c in cabPts)
    {
        var d = c - a; var hits = UnityEngine.Physics.RaycastAll(a, d.normalized, d.magnitude + 0.5f, ~0, UnityEngine.QueryTriggerInteraction.Ignore);
        System.Array.Sort(hits, (p, q) => p.distance.CompareTo(q.distance));
        bool vis = true;
        foreach (var h in hits) { if (IsUnder(h.collider.transform, tower)) break; if (h.distance < d.magnitude - 0.3f) { vis = false; if (blocker == "") blocker = h.collider.transform.parent != null ? h.collider.transform.parent.name + "/" + h.collider.name : h.collider.name; break; } }
        if (vis) seen++;
    }
    md.AppendLine("| " + j.n + " | " + seen + " | " + (seen == cabPts.Count ? "none" : blocker) + " |");
    junc += j.n + " " + (seen > 0 ? "yes" : "no") + " (" + seen + "); ";
}

// ---------------- next destination from the junctions Marlow found blind (8.9a), eye 1.6 m, trees on ----------------
bool SeesPoint(UnityEngine.Vector3 a, UnityEngine.Vector3 tgt, UnityEngine.Transform goal, out string blocker)   // a hit on the goal object counts as seen
{
    var d = tgt - a; var hits = UnityEngine.Physics.RaycastAll(a, d.normalized, d.magnitude, ~0, UnityEngine.QueryTriggerInteraction.Ignore);
    System.Array.Sort(hits, (p, q) => p.distance.CompareTo(q.distance)); blocker = "";
    foreach (var h in hits) { if (IsUnder(h.collider.transform, goal)) return true; if (UnityEngine.Vector3.Distance(h.point, tgt) < 1.5f) return true; blocker = (h.collider.transform.parent != null ? h.collider.transform.parent.name + "/" : "") + h.collider.name; return false; }
    return true;
}
var snagT = giants.Find("Heroes/Snag"); var boathouseT = Root("Lake").transform.Find("Boathouse");
var nexts = new (string from, UnityEngine.Vector2 at, string to, UnityEngine.Vector3[] tgts, UnityEngine.Transform goal)[] {
    ("Pump (190, 97)", new UnityEngine.Vector2(190f, 97f), "the Snag (W1 to Camp 3)", new[] { V(96f, 54f, 146.5f), V(98.7f, 45f, 145.2f), V(98.7f, 30f, 145.2f) }, snagT),
    ("Camp 2, 8 m out toward the lake (286.5, 102.2)", new UnityEngine.Vector2(286.5f, 102.2f), "boathouse roof", new[] { V(240f, -1.0f, 52.4f), V(242.8f, -1.2f, 52.4f), V(240f, -1.0f, 55.0f) }, boathouseT),
    ("Camp 3 floor (79, 145)", new UnityEngine.Vector2(79f, 145f), "tower cab", cabPts.ToArray(), tower),
    ("Camp 3 centre (78, 146)", new UnityEngine.Vector2(78f, 146f), "tower cab", cabPts.ToArray(), tower),
};
md.AppendLine("\n## Next destination from the junctions found blind in the walk (eye 1.6 m, trees and thicket on)\n");
md.AppendLine("| From | Toward | Points seen | First blocker of a missed ray |");
md.AppendLine("|---|---|---|---|");
string nextLine = ""; bool nextAll = true;
foreach (var nx in nexts)
{
    var a = V(nx.at.x, Hg(nx.at.x, nx.at.y) + 1.6f, nx.at.y); int seenN = 0; string blk = "";
    foreach (var tp in nx.tgts) { if (SeesPoint(a, tp, nx.goal, out var b)) seenN++; else if (blk == "") blk = b; }
    if (seenN == 0) nextAll = false;
    md.AppendLine("| " + nx.from + " | " + nx.to + " | " + seenN + " of " + nx.tgts.Length + " | " + (blk == "" ? "none" : blk) + " |");
    nextLine += nx.from + " " + seenN + "/" + nx.tgts.Length + "; ";
}
// ---------------- Hollow Giant crown against the Camp 2 view (cone rule 3 m, 5.2) ----------------
var hgCrown = giants.Find("Heroes/Hollow_Giant/Crown"); float crownClear = float.MaxValue;
if (hgCrown != null)
{
    var mfC = hgCrown.GetComponent<UnityEngine.MeshFilter>().sharedMesh; var eyeC = V(tower.position.x, heights[0].Item2, tower.position.z);
    var camp2Tgts = new[] { V(292f, 24.2f, 108f), V(287.2f, 24f, 108f), V(292f, 24f, 103.2f), V(292f, 24f, 112.8f), V(296.8f, 24f, 108f) };
    foreach (var v in mfC.vertices)
    {
        var wv = hgCrown.TransformPoint(v);
        foreach (var t in camp2Tgts) { var ab = t - eyeC; float s = UnityEngine.Mathf.Clamp01(UnityEngine.Vector3.Dot(wv - eyeC, ab) / ab.sqrMagnitude); crownClear = UnityEngine.Mathf.Min(crownClear, UnityEngine.Vector3.Distance(wv, eyeC + ab * s)); }
    }
}
md.AppendLine("\nHollow Giant crown to the deck-centre lines to the Camp 2 stack top and its edges: " + crownClear.ToString("F1") + " m (cone rule 3 m).");
md.AppendLine("\n## Result\n");
md.AppendLine("- Places: " + summary);
md.AppendLine("- Ward hidden from every eye point (W-1, with +3 m): " + (wardHidden ? "yes" : "NO") + ". Cave hidden (C-1, with +3 m): " + (caveHidden ? "yes" : "NO") + ".");
md.AppendLine("- " + headline);
md.AppendLine("- Cab from junctions: " + junc);
md.AppendLine("- W-1 with eyes and targets raised 3 m keeps " + w1Plus3.ToString("F1") + " m (needs 3): " + (w1Plus3 >= 3f ? "yes" : "NO") + ".");
md.AppendLine("- Next destination from the blind junctions: " + nextLine + (nextAll ? "all seen" : "NOT ALL SEEN"));
md.AppendLine("- Hollow Giant crown clearance to the Camp 2 lines: " + crownClear.ToString("F1") + " m (needs 3): " + (crownClear >= 3f ? "yes" : "NO") + ".");

foreach (var c in temp) UnityEngine.Object.DestroyImmediate(c);
if (!wasDirty) UnityEditor.SceneManagement.EditorSceneManager.SaveScene(scene);   // the temporary colliders are gone; saving the identical scene clears the dirty flag
string outPath = System.IO.Path.GetFullPath("Docs/Layout/Main3/Main3_sightlines.md");
System.IO.File.WriteAllText(outPath, md.ToString());
return "places: " + summary + " | all seen: " + allPlaces + " | Ward hidden: " + wardHidden + ", cave hidden: " + caveHidden + " | " + headline + "| W-1 +3 m " + w1Plus3.ToString("F1") + " ok " + (w1Plus3 >= 3f) + " | next: " + nextLine + "all " + nextAll + " | Hollow Giant crown clearance " + crownClear.ToString("F1") + " ok " + (crownClear >= 3f) + " | cab from junctions: " + junc + "| report " + outPath;
